### ISSUE TITLE
拖动改变位置后，点删除是删除的原来位置的item。想在onItemMoved中加notifyDataSetChanged();刷新一下，但是会显示错乱

### ISSUE THREAD

**Issue by 840631861** [huxq17/HandyGridView#1]
拖动改变位置后，点删除是删除的原来位置的item。想在onItemMoved中加notifyDataSetChanged();刷新一下，但是会显示错乱

**Comment by huxq17** [comment]
能一边拖动一边删除？你怎么删除的？

**Comment by 840631861** [comment]
是拖动完删除，比如把第五个拖到第二个位置，点删除此时的第二个，会删掉第五个位置上的

**Comment by huxq17** [comment]
你在onItemMoved里做数据交换了没有？

**Comment by 840631861** [comment]
交换了 就是照着您demo里的

**Comment by huxq17** [comment]
那你看看demo里有这个问题么

**Comment by 840631861** [comment]
有的

**Comment by huxq17** [comment]
我看了下确实有问题，是因为交换位置的时候没有更新标签里的position，和库无关，做下处理就好了，demo等下更新。

**Comment by huxq17** [comment]
已经可以了，你可以参考demo里的实现。

**Comment by 840631861** [comment]
好的，我试一下
