### ISSUE TITLE
一排6个以上小块 滑动的问题

### ISSUE THREAD

**Issue by liangyongde** [huxq17/HandyGridView#2]
一排超过6个 快速左右滑动，有小块会卡死，放手后小块覆盖。求作者帮解决

**Comment by huxq17** [comment]
你试过4个或者更少的时候就不卡了么？

**Comment by huxq17** [comment]
我试了没问题，你确定是库的问题么

**Comment by liangyongde** [comment]
4个以内不卡 ，我把mDuration的值改小了就好用了，感谢大神的GridView。 操作的视频我发到你邮箱了

**Comment by huxq17** [comment]
能发个有问题的demo么，我看看

**Comment by huxq17** [comment]
上次更新应该解决了这个问题，问题是因为手指释放以后，执行item交换的动画，但是gridview重绘了以后动画仍然在执行，就导致了这个问题，现在在gridview重绘以后停止所有动画，最新版已经解决了这个问题
