### ISSUE TITLE
怎么让前两个固定不移动？？

### ISSUE THREAD

**Issue by gjmm123** [huxq17/HandyGridView#6]
怎么判断是否按下的或者移动到的位置是第一个条目，第一、二个条目想让他固定不变

**Comment by huxq17** [comment]
可以通过OnItemMovedListener 的isFixed()来控制，如果第一，二个条目固定，可以参考下面的代码。

    public boolean isFixed(int position) {
        //When postion==0,the item can not be dragged.
        if (position == 0||position==1) {
            return true;
        }
        return false;
    }

**Comment by gjmm123** [comment]
好的，实现了，谢谢
